all: 
	@g++ -std=c++17 -c mergeStrings.cpp -o build/mergeStrings.o
	@echo "successfully compiled" 
	g++ build/mergeStrings.o -o mergeStrings 

clean: 
	@rm -f ./*.o 
	@rm -f ./builf/*.o
	@echo "object files removed"
